### ISSUE TITLE
`Time DailyRollingFileAppender::calculateNextRolloverTime(const Time& t)` not consider timezone

### ISSUE THREAD

**Issue by sangechen** [log4cplus/log4cplus#136]
if timezone is not UTC, then rollover won't happen at midnight!
the bug happens when call `round_time...` function, as time_t=0 is not midnight.

``` cpp
    case DAILY:
        return round_time_and_add (t, Time (24 * 60 * 60));
```

fix: use localtime() to get `struct tm`, manipulate it according to `DailyRollingFileSchedule`. re-assign it back to Time.

``` cpp

static
Time
get_next_rollover_time (DailyRollingFileSchedule sch, const Time& t, bool use_gmtime = false)
{
    Time result(t.sec(), 0);

    struct tm time;
    if (use_gmtime)
        result.gmtime(&time);
    else
        result.localtime(&time);

    time.tm_isdst = 0;
    switch (sch)
    {
    case MONTHLY:
        time.tm_mon += 1; //next month
        time.tm_mday = 1; //first day
        time.tm_hour = 0;
        time.tm_min = 0;
        time.tm_sec = 0;
        break;

    case WEEKLY:
        time.tm_mday += (7 - time.tm_wday); //next Sunday
        time.tm_hour = 0;
        time.tm_min = 0;
        time.tm_sec = 0;
        break;

    case DAILY:
        time.tm_mday += 1; //next day
        time.tm_hour = 0;
        time.tm_min = 0;
        time.tm_sec = 0;
        break;

    case TWICE_DAILY:
        if(time.tm_hour >= 12) {
            time.tm_mday += 1; //next day
            time.tm_hour = 0;
        }
        else {
            time.tm_hour = 12;
        }
        time.tm_min = 0;
        time.tm_sec = 0;
        break;

    case HOURLY:
        time.tm_min = 0;
        time.tm_sec = 0;
        break;

    case MINUTELY:
        time.tm_sec = 0;
        break;
    };
    result.setTime(&time);

    return result;
}

```

**Comment by wilx** [comment]
@sangechen I have pushed a revision (see above) to my repository that should fix this issue. Please test it and let me know if it works for you. I have used slightly different approach. I want to avoid `struct tm`.

**Comment by CuteLasty** [comment]
Hi Bug #136 still exist.

When your local time less then UTC+N time, the nextRollovertime will adjust to the same day begin time.

For example:
Local time now is Mar 1 00:09:38, after adjust will be Mar 1 00:00:00.

I guess, can you adjust time by those steps?

Time now = chrono::system_clok::now();  //UTC

struct tm time;
localTime(&time, now);   // Convert to Local Time

time.tm_sec = 0;
tm_hour = 0;
tm_min = 0;     // Adjust local time to 00:00:00

DayBegin = from_struct_tm(&time); // convert back to UTC

DayBegin += chrono::seconds(24 * 60 * 60);  // UCT time + 24hrs

**Comment by wilx** [comment]
@CuteLasty Is this related to the initial rollover time in `DailyRollingFileAppender::init()`?

**Comment by wilx** [comment]
@CuteLasty It seems to me it should not be an issue in recent versions any more. There is code in place to adjust for time zone:

```cpp
    case DAILY:
    {
        Time next = round_time_and_add (t, chrono::seconds (24 * 60 * 60));
        return adjust_for_time_zone (next, local_time_offset (next));
    }

...

static
std::chrono::seconds
local_time_offset (Time const & t)
{
    tm time_local, time_gmt;

    helpers::localTime (&time_local, t);
    helpers::gmTime (&time_gmt, t);

    Time t2 = helpers::from_struct_tm (&time_local);
    Time t3 = helpers::from_struct_tm (&time_gmt);

    return std::chrono::duration_cast<std::chrono::seconds> (t2 - t3);
}

static
Time
adjust_for_time_zone (Time const & t, std::chrono::seconds const & tzoffset)
{
    return helpers::time_cast (t - tzoffset);
}
```

**Comment by CuteLasty** [comment]
The round_time_and_add() function used std::fmod() to adjust time from any to 00:00:00 then add 24 hrs.

My time zone is UTC+8, and it's mean my local time is UTC time + 8 hrs.
When my local time is 2017/3/1 00:00:00, it's mean UTC time is 2017/2/28 16:00:00.

After round_time_and_add() adjust 2017/2/28 16:00:00 is 2017/3/1 00:00:00.
2017/3/1 00:00:00 + 8 hrs is 2017/3/1 08:00:00 (UTC).

But, correct time should be 2017/3/2 00:00:00 (UTC+8) or 2017/3/1 16:00:00 (UTC)

The problem is in round_time() return incorrect time.

**Comment by wilx** [comment]
@CuteLasty I guess I can see what you mean. However, I do not immediately see how to fix this. Feel free to suggest a code change/fix.

**Comment by wilx** [comment]
What about reversing the adding and rounding operation: adding first and then rounding down?

**Comment by wilx** [comment]
Well, maybe we should just use the `mktime`'s ability to adjust for out of range values like this:

```cpp
    case DAILY:
    {
        struct tm nextDay;
        helpers::localTime(&nextDay, t);
        nextDay.t_mday += 1;
        nextDay.t_isdst = -1;

        Time ret;
        try
        {
            ret = helpers::from_struct_tm (&nextDay);
        }
        catch (std::runtime_error const & e)
        {
            helpers::getLogLog().error(
                LOG4CPLUS_TEXT("DailyRollingFileAppender::calculateNextRolloverTime()-")
                LOG4CPLUS_TEXT(" from_struct_tm() returned error: ")
                + LOG4CPLUS_C_STR_TO_TSTRING (e.what ()));
            // Set next rollover to 24 hours in future.
            ret = round_time (t, chrono::seconds (60 * 60))
                + chrono::seconds (24 * 60 * 60);
        }

        return ret;
    }
```

**Comment by CuteLasty** [comment]
I just give 'DAILY' as an example, but I think all schedule which called round_time() may have problem.

I have no code use log4cplus now. I only need a daily check for my project. I reference log4cplus code and found this issue.

I only need daily, so what I did is:
Time now = chrono::system_clok::now();  //UTC
struct tm time;
localTime(&time, now);   // UTC to Local

time.tm_sec = 0;
tm_hour = 0;
tm_min = 0;     // Adjust local time to 00:00:00

DayBegin = from_struct_tm(&time); // Local to UTC
DayBegin += chrono::seconds(24 * 60 * 60);  // UCT time + 24hrs

My suggests is:
std::chrono is UTC time, all calculate use UTC time.

Convert it to local time, do check and adjust in local time.
Convert it back to UTC
Calculate next schedule time in std::chrono::time_point
UTC time += next schedule time.

**Comment by wilx** [comment]
@CuteLasty Your English is fine.

Could you please take a look at and test https://github.com/wilx/log4cplus/tree/2.0.x-gh-136 branch? I have reworked the rollover calculation to use `struct tm` and the ability of `mktime()` to normalize its fields during conversion.

**Comment by wilx** [comment]
> Remove adjust time code in DailyRollingFileAppender::init(), and move that code into DailyRollingFileAppender::calculateNextRolloverTime().

This sounds reasonable. I will try to do this.

**Comment by CuteLasty** [comment]
> Could you please take a look at and test https://github.com/wilx/log4cplus/tree/2.0.x-gh-136 branch? 
ok

**Comment by CuteLasty** [comment]
For MONTHLY, you should change this. It is 1, not 0.  tm_mday range is [1, 31].
next.tm_mday = 1; // Round up to next month start

For WEEKLY, If your target time is every next week Monday 00:00:00 (local time), that looks correct.

For DAILY, if your target time is next day 00:00:00 (local time), that looks correct.

For TWICE_DAILY, if your target time is..
Now time: 00:00:00 AM ~ 11:59:59 AM -> Today 12:00:00 AM
Now time: 12:00:00 PM ~ 11:59:59 PM -> Next day 00:00:00 AM
that looks correct.

For HOURLY, it's correct.

For MINUTELY, it's correct.

**Comment by wilx** [comment]
@CuteLasty Thank you for the review. I have done the adjustment and I am going to merge  https://github.com/log4cplus/log4cplus/pull/223 once CI builds finish.

**Comment by CuteLasty** [comment]
Well, it force me to learn std::chrono.

**Comment by wilx** [comment]
This should be fixed now. Please re-open this or a fill a new issue if you still observe any issues.
